model_list:
  - model_name: "Claude 4.5 Haiku"
    litellm_params:
      model: 'vertex_ai/claude-haiku-4-5@20251001'
      vertex_project: 'beyond-chat-1111'
      vertex_location: 'europe-west1'
  - model_name: "Claude Sonnet 4.5"
    litellm_params:
      model: 'vertex_ai/claude-sonnet-4-5@20250929'
      vertex_project: 'beyond-chat-1111'
      vertex_location: 'europe-west1'
  - model_name: "Google 2.5 Flash"
    litellm_params:
      model: 'gemini-2.5-flash'
      vertex_project: 'beyond-chat-1111'
      vertex_location: 'europe-west4'
  - model_name: "Google 2.5 Pro"
    litellm_params:
      model: 'gemini-2.5-pro'
      vertex_project: 'beyond-chat-1111'
      vertex_location: 'europe-west4'
  - model_name: "GPT o3"
    litellm_params:
      model: "azure/o3"
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_API_KEY
      api_version: "2024-12-01-preview"
  - model_name: "GPT o4-mini"
    litellm_params:
      model: "azure/o4-mini"
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_API_KEY
      api_version: "2024-12-01-preview"
  - model_name: "GPT-5"
    litellm_params:
      model: "azure/gpt-5"
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_API_KEY
      reasoning_effort: "minimal"
  - model_name: "GPT-5 mini"
    litellm_params:
      model: "azure/gpt-5-mini"
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_API_KEY
      reasoning_effort: "minimal"
      api_version: "2025-04-01-preview"
  - model_name: "GPT-5.1 instant"
    litellm_params:
      model: "azure/gpt-5.1-chat"
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_API_KEY
      reasoning_effort: "minimal"
  - model_name: "GPT-5.1 thinking"
    litellm_params:
      model: "azure/gpt-5.1"
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_API_KEY
  - model_name: "GPT-5 nano"
    litellm_params:
      model: "azure/gpt-5-nano"
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_API_KEY
      reasoning_effort: "minimal"
  - model_name: "Grok 4"
    litellm_params:
      model: 'xai/grok-4'
      api_key: os.environ/XAI_API_KEY
  - model_name: "Mistral Large 2"
    litellm_params:
      model: 'vertex_ai/mistral-large-2411@001'
      vertex_project: 'beyond-chat-1111'
      vertex_location: 'europe-west4'
  - model_name: "Perplexity Sonar Deep Research"
    litellm_params:
      model: 'perplexity/sonar-deep-research'
      api_key: os.environ/PERPLEXITYAI_API_KEY
  - model_name: "Perplexity Sonar Pro"
    litellm_params:
      model: 'perplexity/sonar-pro'
      api_key: os.environ/PERPLEXITYAI_API_KEY
  - model_name: "Perplexity Sonar Reasoning Pro"
    litellm_params:
      model: 'perplexity/sonar-reasoning-pro'
      api_key: os.environ/PERPLEXITYAI_API_KEY
  - model_name: "GPT OSS 120b"
    litellm_params:
      model: "azure/gpt-oss-120b"
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_API_KEY
  - model_name: "Grok 4 fast (thinking)"
    litellm_params:
      model: "azure/grok-4-fast-reasoning"
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_API_KEY
  - model_name: "Grok 4 fast (instant)"
    litellm_params:
      model: "azure/grok-4-fast-non-reasoning"
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_API_KEY
  - model_name: "Mistral Large 3"
    litellm_params:
      model: "azure/Mistral-Large-3"
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_API_KEY
  - model_name: "DeepSeek-V3.2"
    litellm_params:
      model: "azure/DeepSeek-V3.2"
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_API_KEY
  - model_name: "DeepSeek R1"
    litellm_params:
      model: "azure/DeepSeek-R1"
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_API_KEY
  - model_name: "GPT-5.1 Codex"
    litellm_params:
      model: "azure/gpt-5.1-codex"
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_API_KEY
  - model_name: "GPT o3 Deep Research"
    litellm_params:
      model: "azure/o3-deep-research"
      api_base: os.environ/AZURE_OPENAI_ALTERNATIVE_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_ALTERNATIVE_API_KEY
      tools:
        - type: "web_search_preview"
  - model_name: "GPT-5.2"
    litellm_params:
      model: "azure/gpt-5.2"
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_API_KEY

litellm_settings:
  drop_params: true # Drop unsupported params from the request body

general_settings:
  alerting: ["slack"]
  alert_types: [
    "llm_exceptions",
    "llm_too_slow",
    "cooldown_deployment",
  ]

  # [OPTIONAL ALERTING ARGS]
  alerting_args:
      outage_alert_ttl: 60           # 1 minute in seconds
      region_outage_alert_ttl: 60    # 1 minute in seconds
      minor_outage_alert_threshold: 5
      major_outage_alert_threshold: 10
      max_outage_alert_list_size: 1000
      log_to_console: true
      log_request_body: true