model_list:
  - model_name: "Claude 4.5 Haiku"
    litellm_params:
      model: 'vertex_ai/claude-haiku-4-5@20251001'
      vertex_project: 'beyond-chat-1111'
      vertex_location: 'europe-west1'
  - model_name: "Claude Sonnet 4.5"
    litellm_params:
      model: 'vertex_ai/claude-sonnet-4-5@20250929'
      vertex_project: 'beyond-chat-1111'
      vertex_location: 'europe-west1'
      max_tokens: 64000
  - model_name: "Google 2.5 Flash"
    litellm_params:
      model: 'gemini-2.5-flash'
      vertex_project: 'beyond-chat-1111'
      vertex_location: 'europe-west4'
  - model_name: "Google 2.5 Pro"
    litellm_params:
      model: 'gemini-2.5-pro'
      vertex_project: 'beyond-chat-1111'
      vertex_location: 'europe-west4'
  - model_name: "GPT o3"
    litellm_params:
      model: "azure/o3"
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_API_KEY
      api_version: "2024-12-01-preview"
  - model_name: "GPT o4-mini"
    litellm_params:
      model: "azure/o4-mini"
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_API_KEY
      api_version: "2024-12-01-preview"
  - model_name: "GPT-5"
    litellm_params:
      model: "azure/gpt-5"
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_API_KEY
      reasoning_effort: "minimal"
  - model_name: "GPT-5 mini"
    litellm_params:
      model: "azure/gpt-5-mini"
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_API_KEY
      reasoning_effort: "minimal"
      api_version: "2025-04-01-preview"
  - model_name: "GPT-5.1 instant"
    litellm_params:
      model: "azure/gpt-5.1-chat"
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_API_KEY
      reasoning_effort: "minimal"
  - model_name: "GPT-5.1 thinking"
    litellm_params:
      model: "azure/gpt-5.1"
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_API_KEY
  - model_name: "GPT-5 nano"
    litellm_params:
      model: "azure/gpt-5-nano"
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_API_KEY
      reasoning_effort: "minimal"
  - model_name: "Grok 4"
    litellm_params:
      model: 'xai/grok-4'
      api_key: os.environ/XAI_API_KEY
  - model_name: "Mistral Large 2"
    litellm_params:
      model: 'vertex_ai/mistral-large-2411@001'
      vertex_project: 'beyond-chat-1111'
      vertex_location: 'europe-west4'
  - model_name: "Perplexity Sonar Deep Research"
    litellm_params:
      model: 'perplexity/sonar-deep-research'
      api_key: os.environ/PERPLEXITYAI_API_KEY
  - model_name: "Perplexity Sonar Pro"
    litellm_params:
      model: 'perplexity/sonar-pro'
      api_key: os.environ/PERPLEXITYAI_API_KEY
  - model_name: "Perplexity Sonar Reasoning Pro"
    litellm_params:
      model: 'perplexity/sonar-reasoning-pro'
      api_key: os.environ/PERPLEXITYAI_API_KEY

litellm_settings:
  drop_params: true # Drop unsupported params from the request body

general_settings:
  alerting: ["slack"]
  alerting_threshold: 300 # sends alerts if requests hang for 5min+ and responses take 5min+
  spend_report_frequency: "1d" # [Optional] set as 1d, 2d, 30d .... Specify how often you want a Spend Report to be sent

  # [OPTIONAL ALERTING ARGS]
  alerting_args:
      daily_report_frequency: 43200  # 12 hours in seconds
      report_check_interval: 3600    # 1 hour in seconds
      budget_alert_ttl: 86400        # 24 hours in seconds
      outage_alert_ttl: 60           # 1 minute in seconds
      region_outage_alert_ttl: 60    # 1 minute in seconds
      minor_outage_alert_threshold: 5
      major_outage_alert_threshold: 10
      max_outage_alert_list_size: 1000
      log_to_console: true
      log_request_body: true